(setq treesit-language-source-alist
    '((bash "https://github.com/tree-sitter/tree-sitter-bash")
  	(c "https://github.com/tree-sitter/tree-sitter-c")
  	(cpp "https://github.com/tree-sitter/tree-sitter-cpp")
  	(c-sharp "https://github.com/tree-sitter/tree-sitter-c-sharp")
  	(commonlisp "https://github.com/theHamsta/tree-sitter-commonlisp")
      (cmake "https://github.com/uyha/tree-sitter-cmake")
      (css "https://github.com/tree-sitter/tree-sitter-css")
  	(dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
      (elisp "https://github.com/Wilfred/tree-sitter-elisp")
  	(erlang "https://github.com/WhatsApp/tree-sitter-erlang/")
      (go "https://github.com/tree-sitter/tree-sitter-go")
  	(gitignore "https://github.com/shunsambongi/tree-sitter-gitignore")
  	(graphql "https://github.com/bkegley/tree-sitter-graphql")
  	(haskell "https://github.com/tree-sitter/tree-sitter-haskell")
      (html "https://github.com/tree-sitter/tree-sitter-html")
  	(java "https://github.com/tree-sitter/tree-sitter-java")
      (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
  	(jq "https://github.com/flurie/tree-sitter-jq")
      (json "https://github.com/tree-sitter/tree-sitter-json")
  	(json5 "https://github.com/Joakker/tree-sitter-json5")
  	(julia "https://github.com/tree-sitter/tree-sitter-julia")
  	(latex "https://github.com/latex-lsp/tree-sitter-latex")
  	(llvm "https://github.com/benwilliamgraham/tree-sitter-llvm")
  	(lua "https://github.com/Azganoth/tree-sitter-lua")
      (make "https://github.com/alemuller/tree-sitter-make")
      (markdown "https://github.com/ikatyang/tree-sitter-markdown")
  	(meson "https://github.com/staysail/tree-sitter-meson")  ;; There is an alternative which supposedly heavily diverges from the official tree-sitter grammer: https://github.com/Decodetalkers/tree-sitter-meson
  	(kotlin "https://github.com/fwcd/tree-sitter-kotlin")
  	(nix "https://github.com/nix-community/tree-sitter-nix")
  	(objc "https://github.com/jiyee/tree-sitter-objc")
  	(ocaml "https://github.com/tree-sitter/tree-sitter-ocaml")
  	(org "https://github.com/milisims/tree-sitter-org")
  	(perl "https://github.com/tree-sitter-perl/tree-sitter-perl") ;; Another option is: https://github.com/ganezdragon/tree-sitter-perl
      (python "https://github.com/tree-sitter/tree-sitter-python")
  	(php "https://github.com/tree-sitter/tree-sitter-php")
  	(r "https://github.com/r-lib/tree-sitter-r")
  	(regex "https://github.com/tree-sitter/tree-sitter-regex")
  	(ruby "https://github.com/tree-sitter/tree-sitter-ruby")
  	(rust "https://github.com/tree-sitter/tree-sitter-rust")
  	(scheme "https://github.com/6cdh/tree-sitter-scheme")
  	(sexp "https://github.com/AbstractMachinesLab/tree-sitter-sexp")
  	(sql "https://github.com/m-novikov/tree-sitter-sql")   ;; Focus on PostgreSQL Syntax
  	(sqlite "https://github.com/dhcmrlchtdj/tree-sitter-sqlite")
      (toml "https://github.com/tree-sitter/tree-sitter-toml")
      (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
      (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
      (yaml "https://github.com/ikatyang/tree-sitter-yaml")
      (zig "https://github.com/maxxnino/tree-sitter-zig")))
