#+TITLE:    Emacs Basic UI Configuration
#+DATE:     [2024-01-04]
#+PROPERTY: header-args:emacs-lisp :tangle ../C01_EmacsConfiguration/lisp/basic_ui.el :mkdirp yes
#+STARTUP:  show2levels hideblocks
#+auto_tangle: t

* Header

#+begin_src emacs-lisp 
  ;;  ____    _    ____ ___ ____   _   _ ___    ____ ___  _   _ _____ ___ ____ 
  ;; | __ )  / \  / ___|_ _/ ___| | | | |_ _|  / ___/ _ \| \ | |  ___|_ _/ ___|
  ;; |  _ \ / _ \ \___ \| | |     | | | || |  | |  | | | |  \| | |_   | | |  _ 
  ;; | |_) / ___ \ ___) | | |___  | |_| || |  | |__| |_| | |\  |  _|  | | |_| |
  ;; |____/_/   \_\____/___\____|  \___/|___|  \____\___/|_| \_|_|   |___\____|
  ;;                                                                           
    
#+end_src
* Basic UI Configuration
** Description
The following variables are used to tweak some of the configuration pieces like font and fontsize so you might need to adjust them for your local machine if you try to use this configuration directly.

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.
** Basic UI Settings
*** Bars and Menus
#+begin_src emacs-lisp
  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room
  (menu-bar-mode -1)          ; Disable the menu bar

#+end_src
*** Startup message
#+begin_src emacs-lisp
  ;; We don't need to see that
  (setq inhibit-startup-message t)

#+end_src
*** Fullscreen Mode
#+begin_src emacs-lisp
  ;; Start Emacs in Fullscreen mode and set transparancy
  (add-hook 'emacs-startup-hook 'toggle-frame-maximized)
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (set-frame-parameter (selected-frame) 'alpha '(95 . 95))
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  (add-to-list 'default-frame-alist '(alpha . (95 . 95)))

#+end_src
*** Column and Line Numbers
#+begin_src emacs-lisp
  ;; Set Column Numbers
  (column-number-mode)
  ;; Set Line Numbers Globally
  (global-display-line-numbers-mode t)
  ;; Adjust Line Numbers Width
  (setq display-line-numbers-width t)

  ;; Enable line numbers for some modes
  (dolist (mode '(text-mode-hook
  			  prog-mode-hook
  			  conf-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 'relative))))

  ;; Disable line numbers for some modes
  (dolist (mode
           '(;;org-mode-hook
  	       term-mode-hook
  	       vterm-mode-hook
  	       shell-mode-hook
  	       eshell-mode-hook
  	       pdf-view-mode-hook
  	       treemacs-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src
*** Don't loose your Cursor
#+begin_src emacs-lisp  
  ;; Set up the visible bell
  (setq visible-bell t)

  ;; Enable Highlight-Line
  (global-hl-line-mode 1)

  ;; Disable Highlight-line for some modes
  (dolist (mode
           '(;;org-mode-hook
  	       term-mode-hook
  	       vterm-mode-hook
  	       shell-mode-hook
  	       eshell-mode-hook
  	       pdf-view-mode-hook))
    (add-hook mode (lambda () (hl-line-mode nil))))
  
#+end_src
*** Line Spacing
#+begin_src emacs-lisp
  ;; Add a little space when displaying buffers
  (setq-default line-spacing 0.12)

#+end_src
*** File Encoding
#+begin_src emacs-lisp
  ;; Set default Encoding to UTF-8
  (set-language-environment "UTF-8")
  (set-default-coding-systems 'utf-8)

#+end_src
*** Battery Status
#+begin_src emacs-lisp 
  ;; Display battery for when in full screen mode
  (display-battery-mode t)
  
#+end_src
*** Dialog Box
Don't show a *windowed dialog* box to keep [[id:3cf0fa83-18b3-4206-a109-f4606a94b8c1][Emacs]] keyboard-driven
#+begin_src emacs-lisp
  ;; Don't show windowed Dialog Box on Prompts
  (setq use-dialog-box nil)
  
#+end_src
*** File Dialog
#+begin_src emacs-lisp
  ;; No file dialog
  (setq use-file-dialog nil)

#+end_src
*** Number of Side Windows

Restrict the number of ~window slots~ available to avoid clutter.
The numbers represent the frame directions in the following order:
~left~ - ~top~ - ~right~ - ~bottom~
#+begin_src emacs-lisp
  ; Number of side window slots at
  ; left - top - right - bottom
  (setq window-sides-slots '(3 0 3 1))
  
#+end_src
*** Popup Windows
#+begin_src emacs-lisp
  ;; No popup windows
  (setq pop-up-windows nil)
  
#+end_src
*** Visual Line Mode

Might add that back later
#+begin_src emacs-lisp :tangle no
  ;; Set Visual Line Mode for text modes only
  ;; Preferred over global-visual-line-mode
  (add-hook 'text-mode-hook 'turn-on-visual-line-mode)

#+end_src
** Winner Mode

~Winner mode~ is a ~global minor mode~ that records the changes in the window configuration (i.e. how the frames are partitioned into windows) so that the changes can be "undone" using the command =winner-undo=.  
#+begin_src emacs-lisp
  ;; Enable Winner Mode
  (winner-mode 1)

#+end_src
** Font Configuration

These ~Fonts~ are using the =pet/default-font-size= variable defined earlier
#+begin_src emacs-lisp
  ;; Set default font face of present
  (when (pet/font-available-p "Iosevka")
		(set-face-attribute 'default nil :font "Iosevka"
							:height pet/default-font-size))

  ;; Set the fixed pitch face
  (when (pet/font-available-p "Iosevka")
		(set-face-attribute 'fixed-pitch nil :font "Iosevka"
							:height pet/default-font-size))

  ;; Set the variable pitch face
  (when (pet/font-available-p "Cantarell")
		(set-face-attribute 'variable-pitch nil :font "Cantarell"
							:height pet/default-font-size
							:weight 'regular))

  ;; (when (member "Cantarell" (font-family-list))
  ;; 	  (set-face-attribute 'variable-pitch nil :font "Cantarell"
  ;; 						  :height pet/default-font-size
							;; :weight 'regular))

  ;; Use specific Fontsets for Symbols
  (setq use-default-font-for-symbols nil)

  ;; Use Symbols Nerd Font as Default Symbols Font, otherwise fall back to Symbola (or else)
  (set-fontset-font t 'unicode "Symbols Nerd Font")
  (set-fontset-font t '(#xF500 . #xF8FF) "Symbols Nerd Font")
  (set-fontset-font t 'unicode "Symbola" nil 'append)
  (set-fontset-font t 'unicode (font-spec :script 'unicode) nil 'append)

#+end_src
** Dired

Add the keybinding =C-x C-j= to <dired-jump>. Also we setup up the *base view* of the directory to *first list* *subdirectories* and then files
#+begin_src emacs-lisp
  ;; Configuring Dired

  ;; The prefixes are arguments given to "ls" by dired
  (setq dired-listing-switches
         "-aghlv --group-directories-first")

  ;; Set dired jump keymap
  (global-set-key (kbd "C-x C-j") 'dired-jump)

#+end_src
** Tab Bar Mode

Here we configure =Tab Bar Mode= to work in a specific way.
First we want new tabs to always open with a *scratch* buffer
:NOTE:
=Tab Bar Mode= was added in ~Emacs 27~
:END:
#+begin_src emacs-lisp
  ;; Tab Bar Mode Setting

  ;; Set new tab to scratch buffer
  (setq tab-bar-new-tab-choice "*scratch*")
  ;; right is default -
  ;; change if you dont like that
  ;; (tab-bar-new-tab-to right)                

  ;; Set the name of the tab to
  ;; match the current buffer
  ;; (setq tab-bar-tab-name-function
  ;;       tab-bar-current-tab-name)

	;; Keyboard Rules
	;; Remove Tab Bar Buttons
	(setq tab-bar-close-button-show nil
		  tab-bar-new-button-show nil
		  ;; tab-bar-button-relief               ;; controls outline of buttons
		  ;; tab-bar-face tab-bar-tab            ;; configure tab face (bgcolor etc.)
		  )

	;; tab bar is not automatically shown
	;; (set 1 to enable)
	(setq tab-bar-show nil)                      

	;; Helper function to get only the name
	;; of current tab
	(defun pet/current-tab-name ()
	  (alist-get 'name (tab-bar--current-tab)))
  
#+end_src

